title : xinyu chen
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# Data Analyst 

# About Me:
I'm Xinyu, a dedicated individual aspiring to become a Data Analyst. With a keen eye for detail and a passion for uncovering insights from data, I am committed to leveraging my skills to drive data-driven decision-making.

### Education 
Currently enrolled in Data Analysis courses at the London School of Economics (LSE).

### work experience
- Currently pursuing self-study and projects to gain hands-on experience in data analysis.

### contact information
Email: xinyuchenn@gmail.com
phone: +447504545986
